---
services:
  backend:
    image: menagerist-backend
    container_name: menagerist-backend
    restart: unless-stopped
    build: backend
  frontend:
    image: menagerist-frontend
    container_name: menagerist-frontend
    restart: unless-stopped
    build: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
