[project]
name = "menagerist"
version = "0.0.0-alpha"
summary = "Menagerist - Collection Manager"
description = "A lightweight, self-hostable platform for organising collections of items, events, and people."
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.17.2",
    "asyncpg>=0.31.0",
    "fastapi>=0.124.4",
    "granian>=2.7.0",
    "pydantic-settings>=2.12.0",
    "sqlalchemy[asyncio]>=2.0.45",
]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "granian[reload]>=2.7.0",
    "httpx>=0.28.1",
    "mypy>=1.19.1",
    "pre-commit>=4.5.0",
    "pydocstyle>=6.3.0",
    "pytest>=9.0.2",
    "pytest-archon>=0.0.7",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.9",
]

[build-system]
requires = [ "hatchling>=0.21.2"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/app"]

[tool.mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
strict = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_return_any = true
show_error_codes = true
explicit_package_bases = true
namespace_packages = true

mypy_path = "src"
files = ["src/app", "tests"]


[tool.pydocstyle]
convention = "google"
add-ignore = ["D212", "D104", "D415"]
add-select = ["D213"]

[tool.black]

[tool.ruff]
fix = true

[tool.ruff.lint]
# Automatically remove unused imports
# Enable the isort (I) and Pyflakes (F) rules
select = ["E", "F", "I", "UP"]
fixable = ["ALL"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["app"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.pytest]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
pythonpath = ["src"]
testpaths = ["tests"]
addopts = ["--cov=src/app", "--cov-report=term-missing"]


[tool.coverage.run]
source = ["src/app"]
omit = ["tests/*", "**/__init__.py"]

[tool.coverage.report]
# Fail the build if coverage drops below this percentage
fail_under = 100
show_missing = true
